version: '3'

services:
  nginx:
    build:
      context: ${CUR_DIR}
    container_name: animal_rec_server
    volumes: 
      - ${CUR_DIR}/code:/usr/share/nginx/html:ro
    ports:
      - 8083:80
    expose:
      - 80
    stdin_open: true
    tty: true
